---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Introduction to R
================

### Moffitt Cancer Center 

-----

:calendar: 2023

:alarm_clock: ??

:office: via [Zoom](https://moffitt.zoom.us/j/99031977384)

:computer: [Moffitt](https://moffitt.org/)

-----

## Setup

The course will be hosted through Zoom with video recordings posted on Ponopto after. 
Links to recorded lectures will be emailed out after class.

<!-- 
* When you're done, put a green post-it on your computer. 
* If you need help, put up a pink post-it.
-->

## Course material

All slides will be made available the day of the lecture with any live-coding notes
posted after the lecture. 
All data used through out the course will be made available in the data folder. 
Quizzes can be found in the class Moodle.

<!--
* Rewrite as links to slides on github once they are made
* [Name of talk](path/to/slides.pdf)
-->



## Questions?

Feel free to ask questions in the [GitHub Issues](https://github.com).

## Overview

This is an 8 week course designed to introduce future users to R and Rstudio.
We will cover data cleaning using the `tidyverse`, creating visuals with `ggplot`,
basic statistical analysis and writing documents with `Rmarkdown`. In the end 
you should be able to: 

<!--
Each instructor should provide a one sentence summary of what participants
will be able to do after thier lecture 
-->

* import and manipulate data into different formats
* create new variables and recode existing ones 
* plot data using the appropriate figure type 
* perform basic statistics
* write Rmarkdown reports

## Who is this course designed for?

Have you never written any code in R or any other programming language? Are you
familiar with R, but hoping to bulk up your basic skills? Have you used R but are
new to the `tidyverse` framework? 

## Materials

Materials will be made available on [GitHub](https://github.com/FridleyLab/Intro_to_R_2023/).  
If you are using an organization-issued laptop, you may want to verify before you 
arrive that you can access GitHub.

## Schedule and Links 

*   May 31 - [Basics of R/RStudio](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=ef316a92-1a87-4ae8-a788-aea70150dd19)
*   June 07 - [Data import and wrangling part I](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d525ac17-661c-44f4-9ad3-aeae0153744a)
*   June 14 - [Data wrangling part II](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=c9dcb86c-d5fe-4662-bfbf-aeb5014a74bb)
*   June 21 - [Visualizations with `ggplot2` part I](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=59d650c7-fb6d-45b7-9146-aebc014f764c)
*   June 28 - [Visualizations with `ggplot2` part II](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=77afb363-11d7-40c5-beff-aec3014a604f)
*   July 05 - [Statistics part I](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=88550b82-b60b-42e3-bba4-aeca0151967b)
*   July 12 - [Statistics part II](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=3ba6f5c1-a058-4d93-85f8-aed1014d746f)
*   July 19 - [`rmarkdown`](https://moffitt.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9382f60b-eb19-4eb4-9426-aed8014ac911)

## Instructors

<!--
Add links to personal websites and double check personal info
* add small blurbs/pictures for each instructor? 
-->

This course is taught by members of Moffitt staff including Jordan
Creed, a data scientist in the Department of Health Informatics, Zachary
Thompson and Ram Thappa, biostatisticians in the Bioinformatics and
Biostatistics Core.

-----